name = "SMP 5.5: Tricky Situation"
author = "enjarai"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3f0a135fb01786385a7196a14f3ca04eb807c1d30bc4a731065535fabc001a54"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
