name = "SMP 5.5: Tricky Situation"
author = "enjarai"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e71174d2f2828b2811317841cb45f81b1b90e7fadfd1df7e31ef176032445f9a"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
