name = "SMP 5.5: Tricky Situation"
author = "enjarai"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6ade1e901f0c7acf9e72704e07b0ffdac4b39c5c82bfab2644a93a594cc4181d"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
