name = "SMP 5.5: Tricky Situation"
author = "enjarai"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1bda1a949ebb863244f7bea05b2eae1854a0a6992a1d9d1385cb4da68237a050"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
